[theme]
base = "light"
primaryColor = "#18181B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F8FAFC"
textColor = "#0F1115"
font = "sans serif"

[server]
maxUploadSize = 200
enableXsrfProtection = false

[browser]
gatherUsageStats = false
